EVIDENCE_MODE_FULL = "full"
EVIDENCE_MODE_FAILURE_ONLY = "failure_only"
EVIDENCE_MODE_SCREENSHOT_ONLY = "screenshot_only"

LEGACY_EVIDENCE_MODE_MAP = {
    "always": EVIDENCE_MODE_FULL,
    "on_failure": EVIDENCE_MODE_FAILURE_ONLY,
    "off": EVIDENCE_MODE_SCREENSHOT_ONLY,
}

VALID_EVIDENCE_MODES = {
    EVIDENCE_MODE_FULL,
    EVIDENCE_MODE_FAILURE_ONLY,
    EVIDENCE_MODE_SCREENSHOT_ONLY,
}
